services:
  blockchain.api:
    image: blockchain.api
    build:
      context: .
      dockerfile: src/Blockchain.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION}

  postgres:
    image: postgres:16
    container_name: icmarkets-postgres
    environment:
      POSTGRES_DB: blockchain
      POSTGRES_USER: icmarkets
      POSTGRES_PASSWORD: icmarkets
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
        
  migrator:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: blockchain-migrator
    depends_on:
      - postgres
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=blockchain;Username=icmarkets;Password=icmarkets
    command: >
      sh -c "dotnet restore &&
             dotnet tool install --global dotnet-ef &&
             export PATH=$PATH:/root/.dotnet/tools &&
             dotnet-ef database update --project src/Blockchain.Infrastructure --startup-project src/Blockchain.Api"

volumes:
  pgdata:
